services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=yourpassword
            - MYSQL_DATABASE=contacts_db
            - MYSQL_USER=app
            - MYSQL_PASSWORD=yourpassword
        ports:
            - "13306:3306"
        networks:
            - laravel

    app:
        image: laravel:latest
        container_name: laravel_app
        build:
            context: .
            dockerfile: .dev-ops/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        env_file:
            - ./.env
        networks:
            - laravel
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    webserver:
        image: nginx:alpine
        container_name: nginx_web
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - .dev-ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
